### ISSUE TITLE
Not valid html when insert dynamic objects in redactor

### ISSUE THREAD

**Issue by pincher2012** [jbroadway/elefant#242]
Dynamic objects are wrapped in paragraph tag when inserting through a visual editor. Markup is not valid, when output of dynamic object contains flow content.

**Comment by jbroadway** [comment]
I haven't found a good solution to fix this since the embed code gets inserted into a `<p>` tag automatically by the Redactor editor. Stripping the outer tag caused other issues when moving copy around in the editor, so I left it in. Aside from the markup passing validation tests, it doesn't cause any visible rendering issues at least.

**Comment by BronyBorn** [comment]
I think there was an update related to this...
Has this issue been fixed?

**Comment by jbroadway** [comment]
Ah yes, it has actually. The parser now looks for an outer `<p>` around the `<span>` as well as any `<br>` tags in the same otherwise empty paragraph.
