### ISSUE TITLE
Responsive theme for new installs

### ISSUE THREAD

**Issue by twheel** [jbroadway/elefant#275]
Suggestion: use [skeleton](http://getskeleton.com/) or another lightweight, responsive theme for the default layout, replacing 960.css.  Advantages: designs would work out of the box on small windows on laptops/desktops; it would mean we didn't need to detect mobile; and we could test responsive designs by resizing a browser window instead of having to upload/view on phone or spoof a mobile device.

I'd be happy to submit a pull request reworking the default layout (changing grid_12, etc. to the equivalents).

**Comment by AxorB** [comment]
I find it a good idea.

**Comment by jbroadway** [comment]
I actually have a really simple theme based on the `admin/util/minimal-grid` that I've been meaning to clean up and replace the existing one with. It's responsive. To fully remove 960.gs, I'll have to remove it from the admin template as well.

This will let us remove the root `css` folder entirely, and also remove the need to call `{! admin/util/minimal-grid !}` inside of many of the admin-facing handlers too.

I'll try to get this cleaned up and pushed to Github this week!

**Comment by twheel** [comment]
So it will be a theme inside of `/layouts/`?

**Comment by jbroadway** [comment]
Yep. It'll be in `layouts/minimal` so it'll be self-contained too. Got the minimal theme itself working, but I still need to fix the Designer app now which broke when I switched the admin theme to minimal-grid too.

**Comment by jbroadway** [comment]
Just pushed the changes for the new [minimal](https://github.com/jbroadway/elefant/tree/master/layouts/minimal) theme. It has a few notable changes:

* Login/user bar included in the template now
* Slideshow changed for a single editable photo
* Logo editable too
* Template components broken out into includes

This also updates the admin template to use the minimal grid as well, and updates existing apps to work with it. That lets us remove the css folder from the root of the site too, so that we're encouraging designers to include CSS with their themes.

Let me know what you think!
